Damping by pass applied to previous displacement
Unity-Technologies/com.unity.cinemachine pull request #219
Opened 2021-03-31 22:28 UTC by gaborkb

### Purpose of this PR

https://jira.unity3d.com/browse/CMCL-118
Described in this forum post: https://forum.unity.com/threads/problem-with-cinemachine-collider.948316/

The problem is that collider's displacement is in world space, and when damping is on and the FreeLook rotates, it does not also rotate the offset that's damping itself away.

Solutions could be either: keep offset in camera-local space, or **apply state's damping bypass to the offset**.

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automated test
- [ ] Passed all automated tests
- [ ] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Samples status

- [ ] Re-packed Extras~/CinemachineExamples.unitypackage

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

### Comments to reviewers

[Info per person for what to focus on, or historical info to understand who have previously reviewed and coverage. Help them get context.]

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

2021-04-06 15:22 UTC, glabute requested changes
It's better, but I don't think this fix does the whole job.  I can still get it to move laterally in this situation.  See the big horizontal displacement of the vcam (yellow line).  If I then rotate to an unobstructed place, there is slow horizontal damping back to normal

![image](https://user-images.githubusercontent.com/6424658/113735542-55aea080-96ca-11eb-9ecd-d597c1d655ad.png)

2021-04-06 15:22 UTC, glabute commented on Runtime/Behaviours/CinemachineCollider.cs
> +                            Quaternion.Euler(state.PositionDampingBypass) * extra.m_previousDisplacement + delta;
This looks fishy.  You use an unrotated prev displacement in the first line.  Shouldn't you rotate it first?

2021-04-09 16:20 UTC, gaborkb commented
> It's better, but I don't think this fix does the whole job. I can still get it to move laterally in this situation. See the big horizontal displacement of the vcam (yellow line). If I then rotate to an unobstructed place, there is slow horizontal damping back to normal
> 
> ![image](https://user-images.githubusercontent.com/6424658/113735542-55aea080-96ca-11eb-9ecd-d597c1d655ad.png)

I think, we should fix that in another PR. Because it think it will be a feature change, not a bug fix.

2021-04-21 12:37 UTC, glabute commented
ok, we can do it in a second pass

2021-04-21 12:38 UTC, glabute approved these changes

2021-04-21 12:38 UTC, merged