game view guides only if inspector expanded, freeLook rigs in tabs
Unity-Technologies/com.unity.cinemachine pull request #223
Opened 2021-04-06 23:39 UTC by glabute

### Purpose of this PR

CMCL-287
Problem: with FramingTransposer/Composer combos and with FreeLooks, multiple game-view guides are drawn on top of each other, and it's difficult to read and to manipulate.

Idea: Only draw the guide if the component subsection is expanded.  That way the user can choose which component to expand and work on, and get the right guides.

For the FreeLook, put the rigs in tabs - only the selected rig has the guides visible.

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

low

### Comments to reviewers

Look also at the CIinemachineNewVirtualCamera  and CinemachineNewFreeLook classes

2021-04-07 05:19 UTC, gaborkb commented
The new UI is great! I am liking it! 👍

2021-04-07 06:51 UTC, gaborkb requested changes
Small change for consistency.

2021-04-07 06:51 UTC, gaborkb commented on Editor/Utility/InspectorUtility.cs
> +    /// Hack for vcams because there's no way to find out if an editor is collaped
I think, it's a nice hack :)

2021-04-07 06:51 UTC, gaborkb commented on Editor/Editors/CinemachineFreeLookEditor.cs
> +        int m_SelectedRig = 1;
This should be static to be consistent with NewFreelook, and vcams FTransposer or Composer

2021-04-07 06:51 UTC, gaborkb commented on Editor/Editors/CinemachineFreeLookEditor.cs
> +                    Target.m_YAxis.Value = m_SelectedRig == 0 ? 1 : (m_SelectedRig == 1 ? 0.5f : 0);
This puzzled me for a while, but now I understand what it does. When you select a rig, this activates the selected rig by moving the vcam rig on the y axis.

2021-04-07 14:16 UTC, gaborkb approved these changes

2021-04-07 14:16 UTC, gaborkb commented on Editor/Editors/CinemachineFreeLookEditor.cs
> +                EditorGUILayout.Separator();
Are the two separators intentional?

2021-04-07 14:16 UTC, gaborkb commented on Editor/Editors/CinemachineVirtualCameraEditor.cs
> +                + "or otherwise driven by script.");
This is very useful!

2021-04-07 14:38 UTC, glabute commented on Editor/Editors/CinemachineVirtualCameraEditor.cs
> +                + "or otherwise driven by script.");
yes

2021-04-07 14:45 UTC, glabute commented on Editor/Editors/CinemachineFreeLookEditor.cs
> +                EditorGUILayout.Separator();
yes

2021-04-12 04:51 UTC, gaborkb approved these changes

2021-04-12 11:13 UTC, glabute commented on Editor/Editors/CinemachineComposerEditor.cs
> +            bool isLive = targets.Length <= 1 && brain.IsLive(vcam, true);
We don't draw draggable guides for multi-select

2021-04-21 12:39 UTC, merged