CMPostprocessing state bug
Unity-Technologies/com.unity.cinemachine pull request #225
Opened 2021-04-08 00:22 UTC by gaborkb

### Purpose of this PR

https://jira.unity3d.com/browse/CMCL-290
Fix a regression in CMPostProcessing.

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automated test
- [ ] Passed all automated tests
- [ ] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Samples status

- [ ] Re-packed Extras~/CinemachineExamples.unitypackage

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

### Comments to reviewers

The problem is only with Framing Transposer, because the state is incorrect in the post aim stage.
Applying PostProcessing in Finalize state fixes this. However, I suspect that there was a reason for applying it post aim. If that's the case, let's discuss a solution. Note, vcam.State.FinalPosition has the correct position value.

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

2021-04-08 00:22 UTC, gaborkb commented
The problem is only with Framing Transposer, because the state is incorrect in the post aim stage.
Applying PostProcessing in Finalize state fixes this. However, I suspect that there was a reason for applying it post aim. If that's the case, let's discuss a solution. Note, vcam.State.FinalPosition has the correct position value.

2021-04-08 21:30 UTC, glabute requested changes
Please add changelog entry

2021-04-08 21:32 UTC, glabute commented
Also: there is similar logic in CinemachineVolumeSettings.cs.  Do we need the same change there too?

2021-04-09 13:42 UTC, glabute approved these changes

2021-04-09 13:44 UTC, merged