WIP
Unity-Technologies/com.unity.cinemachine pull request #231
Opened 2021-04-20 05:28 UTC by gaborkb

[Delete any line or section that does not apply]

### Purpose of this PR

[JIRA issue. Desc of feature/change. Links to screenshots, design docs, user docs, etc. Remember reviewers may be outside your team, and not know your feature/area that should be explained more.]

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automated test
- [ ] Passed all automated tests
- [ ] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Samples status

- [ ] Re-packed Extras~/CinemachineExamples.unitypackage

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

### Comments to reviewers

[Info per person for what to focus on, or historical info to understand who have previously reviewed and coverage. Help them get context.]

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

2021-04-20 07:11 UTC, gaborkb commented
I am not entirely sure about the use case. I tested only that I can set a layer that will make the volume invisible.

2021-04-21 14:09 UTC, glabute requested changes
Maybe we need to think about whether an advanced setting is the right solution.

2021-04-21 14:12 UTC, glabute commented on Runtime/PostProcessing/CinemachineVolumeSettings.cs
> +        public static bool s_LayerMaskOverrideEnabled;
Why static?  Having it as a global setting does not respond to the needs.  If you read the forum post, the guy wants a per-camera setting.

2021-04-21 20:52 UTC, gaborkb commented on Runtime/PostProcessing/CinemachineVolumeSettings.cs
> +            var volumes = GetDynamicBrainVolumes(brain, numBlendables, currentVolume);
I dislike this part. We could discuss a better solution.

2021-04-23 15:13 UTC, gaborkb commented
Marked draft until we come back to it.

2023-02-01 14:03 UTC, gaborkb commented
See https://jira.unity3d.com/browse/CMCL-284 for more info.

2023-02-01 14:03 UTC, closed without merging