ReferenceUp is not correct in CameraState Lerp
Unity-Technologies/com.unity.cinemachine pull request #256
Opened 2021-05-11 15:33 UTC by gaborkb

### Purpose of this PR

https://jira.unity3d.com/browse/CMCL-315

I am not sure about the fix. I am a bit afraid that somewhere something expects the Lerp result to have a ReferenceUp that is the same as Brain World up. 

The State Lerp code clearly expects the reference up to be dependent on the orientation of the vcam.
`state.ReferenceUp = Vector3.Slerp(stateA.RawOrientation * Vector3.up, stateB.RawOrientation * Vector3.up, t);`

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested. But not extensively. Tested with different cinemachine body and aim components and with a couple of different rotations.

### Documentation status

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Samples status

- [ ] Re-packed Extras~/CinemachineExamples.unitypackage

### Technical risk

Low, but see Purpose of PR

### Comments to reviewers

I am not sure about the fix. I am a bit afraid that somewhere something expects the Lerp result to have a ReferenceUp that is the same as Brain World up. 

The State Lerp code clearly expects the reference up to be dependent on the orientation of the vcam.
`state.ReferenceUp = Vector3.Slerp(stateA.RawOrientation * Vector3.up, stateB.RawOrientation * Vector3.up, t);`

### Package version

- [ ] Updated package version

2021-05-12 20:00 UTC, glabute requested changes

2021-05-18 14:13 UTC, glabute requested changes
I was still getting a pop when I tested with the repro project.
Pushed a fix to address it.
Please review and verify.

2021-05-18 14:26 UTC, gaborkb commented
> I was still getting a pop when I tested with the repro project.
> Pushed a fix to address it.
> Please review and verify.

I had a slightly modified version of the repro project and there the pop was not visible. I re-downloaded the original repro project and it was clearly visible there! Good Catch! 👍 

I verified and with your changes the pop is gone is both  projects (repro project and my modified version).

2021-05-19 11:55 UTC, glabute approved these changes

2021-05-19 11:55 UTC, merged