CMCL-570: Refactored menu based creation to be consistent with the rest of Unity
Unity-Technologies/com.unity.cinemachine pull request #322
Opened 2021-10-13 05:33 UTC by MechWarrior99

### Purpose of this PR
The current implementation used to create Cinemachine Cameras in the Hierarchy is inconsistent with the rest of Unity. This leads to Cinemachine feeling lower quality and some things to not produce the expected result.
Main changes
- Names of created objects are now consistent with the rest of Unity. Example being "Vcam" is now "Virtual Camera".
- Duplicate names of created objects is now consistent with the rest of Unity. Example being "Vcam1" is now "Virtual Camera (1)". This will also support the "Game Object Naming" scheme setting option that is present in newer versions of Unity.
- It is now easier to add more options to the menu later with less boilerplate and places for failure.

### Testing status
Manually used each menu item and ensured that the resulting GameObjects and components are the same as the current implementation.
Each menu item was manually tested with both undo and redo.

- [x] Manually tested 

### Documentation status

- [x] Commented all public classes, properties, and methods

### Technical risk
There were definitions for versions < 2019.3 which were removed as the minimum Unity version for the package is 2019.4. This should not cause any problems but worth mentioning.

~`CinemachineEditorAnalytics.SendCreateEvent(string name)` is now sent for each object that is created instead of per menu item. The name that is sent is also the same as the non-unique name of the object that is created. 
This results in slightly less specific names for the events, and a slightly higher number. I don't suspect that this will be a problem, but is a significant enough change that it is worth mentioning.~

### Comments to reviewers
Currently names of created GameObjects are the same as the menu items, but perhaps they would be better being more explicit? For example "Mixing Virtual Camera" instead of "Mixing Camera", however doing so does make the names relatively longer.
~The "2D Camera" item also creates a GameObject called "2D Camera", I'm not sure if it would be better to just call it "Virtual Camera" instead like it was.~

2021-10-18 14:16 UTC, glabute commented on Editor/Utility/InspectorUtility.cs
> -            return ObjectFactory.CreateGameObject(name, types);
You can't delete this because it's a public API.  Instead, deprecate it.

2021-10-18 17:33 UTC, glabute commented
Thanks for the PR.  Nice work.
Probably the change in analytics will have to be reverted.
Notes on style for future reference:
- Unity is moving towards a "leave out what is redundant" style, which implies that labeling fields and methods "private" is undesirable, since they are that way by default
- Lines more than 100 characters or so wide should be split.  Sidescrolling is evil.

2021-11-09 13:39 UTC, gaborkb requested changes

2021-11-09 13:39 UTC, gaborkb commented on Editor/Menus/CinemachineMenu.cs
> +            CinemachineEditorAnalytics.SendCreateEvent("Virtual Camera");
This changed from 2D camera to Virtual Camera.

2021-11-09 13:39 UTC, gaborkb commented on Editor/Timeline/CinemachineShotEditor.cs
> +            CinemachineEditorAnalytics.SendCreateEvent("Virtual Camera");
This is new analytics. The Create Event analytics is specifically for the Create Menu. I don't think this is wanted.

2021-11-12 18:12 UTC, gaborkb approved these changes

2021-11-12 18:12 UTC, merged