CMCL-339: Near Clip Plane negative value not kept if override not set to Orthographic
Unity-Technologies/com.unity.cinemachine pull request #336
Opened 2021-10-27 17:42 UTC by gaborkb

### Purpose of this PR

Fix for https://jira.unity3d.com/browse/CMCL-339

Fix:
- Validate near clip plane when pulling values from camera.

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Samples status

- [ ] Re-packed Extras~/CinemachineExamples.unitypackage

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

### Comments to reviewers

[Info per person for what to focus on, or historical info to understand who have previously reviewed and coverage. Help them get context.]

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

2021-11-02 09:01 UTC, gaborkb commented
I think a better alternative would be something like this, but it is an API change (or a new API):
`public void Validate(CinemachineBrain brain)
        {
            if (brain != null)
                SnapshotCameraReadOnlyProperties(brain.OutputCamera);
            if (!Orthographic)
                NearClipPlane = Mathf.Max(NearClipPlane, 0.001f);
            // ...`

2021-11-02 12:26 UTC, glabute requested changes
I don't like this fix.  Already it is very confusing with the flags and the overrides, and this makes it worse.  
What about removing the NearClipPlane check from OnValidate?  The check could be put in the property drawer instead.  Then you wouldn't need the flag.

2021-11-02 13:47 UTC, gaborkb commented
> I don't like this fix. Already it is very confusing with the flags and the overrides, and this makes it worse. What about removing the NearClipPlane check from OnValidate? The check could be put in the property drawer instead. Then you wouldn't need the flag.

Me neither. :) I wanted to talk to you before review, I added the flag just to highlight what's wrong. I like your alternative :)

2021-11-03 14:01 UTC, glabute reviewed
Code is good, but

2021-11-03 14:02 UTC, glabute requested changes
Code is good but missing changelog and PR description is stale

2021-11-03 14:18 UTC, glabute approved these changes

2021-11-03 15:07 UTC, merged