CMCL-644: Freelook recentering is affected by Time Scale even with Ignore Time Scale on
Unity-Technologies/com.unity.cinemachine pull request #356
Opened 2021-11-19 17:27 UTC by gaborkb

### Purpose of this PR

https://jira.unity3d.com/browse/CMCL-644
The problem came from inconsistencies and delta time in user input handling. Now delta time is always real delta time for input.

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

### Comments to reviewers

### Package version

2021-11-23 17:09 UTC, glabute requested changes

2021-11-23 17:09 UTC, glabute commented on Runtime/Core/AxisState.cs
> -            // Cheating: we want the render frame time, not the fixed frame time
you need to leave this comment, or something like it. What's going on isn't obvious because the caller is passing in deltaTime

2021-11-23 17:09 UTC, glabute commented on Runtime/Core/AxisState.cs
> -            else if (Time.inFixedTimeStep && deltaTime >= 0 && m_LastUpdateTime != 0)
you lost the important check for `if (deltaTime >= 0 && m_LastUpdateTime != 0)`

2021-11-23 17:09 UTC, glabute commented on Runtime/Core/AxisState.cs
> +                deltaTime = Time.realtimeSinceStartup - m_LastUpdateTime;
you need to comment why we're setting deltaTime even though the user passed it in.  Also, you need to add some checks (same as above).  You can't just blindly set this.  deltaTime < 0 has special meaning in CM.

2021-11-26 13:14 UTC, glabute approved these changes

2021-11-26 19:56 UTC, gaborkb commented
Freelook tests are no longer deterministic, because it uses deltaTime (before it was using `deltaTime = CinemachineCore.UniformDeltaTimeOverride`).
Should we remove them?

2021-12-01 22:44 UTC, glabute approved these changes

2021-12-03 19:03 UTC, merged