CMCL-633: backports for 2.8.3
Unity-Technologies/com.unity.cinemachine pull request #358
Opened 2021-11-22 19:00 UTC by mjmvisser

### Purpose of this PR

Prep for 2.8.3:
- Backported  regression fix for CMCL-608: cannot change camera projection (#339)
- Backported regression fix for CMCL-657: compilation errors when physics module removed (#361)
- Backported updates to yamato to run tests with and without default packages/modules
- Moved changelog entries to 2.8.3 section
- Made `public Vector3 AimTarget { get; private set; }` private, no new APIs in patch release
- Bumped package version to 2.8.3

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [x] Passed all automated tests
- [x] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [X] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)

### Technical risk

Low

### Comments to reviewers

None

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [X] Updated package version to 2.8.3

2021-11-24 13:44 UTC, glabute requested changes

2021-11-24 13:44 UTC, glabute commented on CHANGELOG.md
> +- Cinemachine3rdPersonAim exposes AimTarget, which is the position of where the player would hit.
this is no longer exposed

2021-11-25 16:43 UTC, gaborkb approved these changes

2021-11-26 16:49 UTC, glabute approved these changes

2021-11-26 20:14 UTC, merged