CMCL-661: remove illegal destructor
Unity-Technologies/com.unity.cinemachine pull request #364
Opened 2021-12-01 23:22 UTC by glabute

### Purpose of this PR

CMCL-661: remove illegal destructor.  Replaced with explicit call to Shutdown() where it was needed.

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Technical risk

low

### Comments to reviewers

Create a vcam, change various parts of the pipeline (Body, Aim, Noise) to different items in the dropdowns.  Be sure to test Do Nothing also.  Test undo/redo.  Try lots of combinations.  Try to break it.  Keep an eye on the console for exceptions.

2021-12-03 16:59 UTC, gaborkb commented
I got this error message, after adding a Composer, then undo, then redo. 
```
MissingReferenceException: The object of type 'CinemachineComposer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Cinemachine.CinemachineComposer.get_IsValid () (at /Users/gaborkb/Documents/Dev/Packages/cinemachine/upm-package-cinemachine/Runtime/Components/CinemachineComposer.cs:130)
Cinemachine.CinemachineComposer.PrePipelineMutateCameraState (Cinemachine.CameraState& curState, System.Single deltaTime) (at /Users/gaborkb/Documents/Dev/Packages/cinemachine/upm-package-cinemachine/Runtime/Components/CinemachineComposer.cs:216)
Cinemachine.CinemachineVirtualCamera.CalculateNewState (UnityEngine.Vector3 worldUp, System.Single deltaTime) (at /Users/gaborkb/Documents/Dev/Packages/cinemachine/upm-package-cinemachine/Runtime/Behaviours/CinemachineVirtualCamera.cs:502)
Cinemachine.CinemachineVirtualCamera.InternalUpdateCameraState (UnityEngine.Vector3 worldUp, System.Single deltaTime) (at /Users/gaborkb/Documents/Dev/Packages/cinemachine/upm-package-cinemachine/Runtime/Behaviours/CinemachineVirtualCamera.cs:155)
Cinemachine.Editor.CinemachineVirtualCameraBaseEditor`1[T].UpdateCameraState () (at /Users/gaborkb/Documents/Dev/Packages/cinemachine/upm-package-cinemachine/Editor/Editors/CinemachineVirtualCameraBaseEditor.cs:94)
UnityEditor.Undo.Internal_CallUndoRedoPerformed () (at /Users/bokken/buildslave/unity/build/Editor/Mono/Undo/Undo.bindings.cs:234)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler() (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:428)
```

2021-12-03 16:59 UTC, gaborkb requested changes
See comment above

2021-12-06 23:01 UTC, glabute commented
In fact this exception exists in master also, it was not introduced by this change.
Fixed it here.

2021-12-07 14:11 UTC, gaborkb approved these changes

2021-12-07 14:18 UTC, merged