CMCL-690: 2.8.4 backports
Unity-Technologies/com.unity.cinemachine pull request #367
Opened 2021-12-08 20:01 UTC by mjmvisser

### Purpose of this PR

backports for CMCL-667, CMCL-661, CMCL-686

### Package version

- [ ] Updated package version to 2.8.4

2021-12-09 20:11 UTC, gaborkb approved these changes

2021-12-10 16:22 UTC, glabute approved these changes

2021-12-11 22:30 UTC, gaborkb approved these changes

2021-12-16 13:52 UTC, gaborkb requested changes
CMCL-622 is not in the backports yet.
PR: https://github.com/Unity-Technologies/com.unity.cinemachine/pull/376

2021-12-16 20:03 UTC, gaborkb approved these changes

2021-12-17 16:12 UTC, merged