CMCL-826: Paste VirtualCamera component onto prefab works for pipeline subcomponents
Unity-Technologies/com.unity.cinemachine pull request #415
Opened 2022-03-08 23:43 UTC by glabute

### Purpose of this PR

Fix for https://jira.unity3d.com/browse/CMCL-829. 

All cases are now correctly handled for VirtualCamera, except when the CinemachineVirtualCamera component values are pasted onto an object that is in the assets folder without entering Prefab mode.  In this case, the subcomponent values are not pasted.  This case cannot be handled easily, and I suggest that we just leave it as is, since there is an easy workaround: enter prefab edit mode.

Still do do: analogous fix for FreeLook.

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

Low

### Comments to reviewers

All combinations need to be tested.  All should succeed or fail gracefully.
- FreeLook/CinemachineVirtualCamera
- Copy component from sceneobject/prefabInAssetFolder/prefabEditMode
- Paste as new component into sceneobject/prefabInAssetFolder/prefabEditMode
- Paste component values into sceneobject/prefabInAssetFolder/prefabEditMode

2022-03-09 19:21 UTC, gaborkb approved these changes
Nice! I manually tested it on my side too.

2022-05-24 16:09 UTC, gaborkb requested changes
All combinations need to be tested.  All should succeed or fail gracefully.
- [x] FreeLook/CinemachineVirtualCamera
- [x] Copy component from sceneobject/prefabInAssetFolder/prefabEditMode
- [x] Paste as new component into sceneobject/prefabInAssetFolder/prefabEditMode. **NOTE**: cannot add to prefabInAssetFolder as new, but I think it is gracefully handled (error message with explanation on Freelook in prefab).
- [x] Paste component values into sceneobject/prefabInAssetFolder/sceneobject. **NOTE**: prefabInAssetFolder does not get the values for the rigs, but sceneobject and sceneobject do.
- [x] Add VirtualCamera/FreeLook component to empty gameobject for sceneobject/prefabInAssetFolder/prefabEditMode. **NOTE**: prefabInAssetFolder handled gracefully.
- [ ] Undo and redo of all combinations and permutations. **NOTE**: Not sure if tested all, but could not undo changes in prefabs.

Additional notes:
Reset crashed my unity on a prefab freelook to which I pasted. 
Reproduce:
1. Create a freelook
2. Make it into prefab
3. Copy some freelook values, and paste it to the prefabInAssetFolder.
4. Click on Reset on prefabInAssetFolder.

2022-05-27 15:28 UTC, glabute commented
I cannot repro the crash

2022-05-27 20:21 UTC, gaborkb commented
> I cannot repro the crash

I cannot reproduce it in 2022.2.0a13 or 2021.3.0f1.
But I can reproduce it in a clean project - unity version 2020.3.34f1.

2022-06-03 14:23 UTC, glabute commented
Still cannot repro

2022-06-03 15:34 UTC, AntoineCharton commented on com.unity.cinemachine/Editor/Editors/CinemachineFreeLookEditor.cs
> +                    MessageType.Error);
Make sure Jessica reviewed the text.

2022-06-03 15:42 UTC, AntoineCharton approved these changes
I didn't experience a crash (Tested on Mac OS). Worked well on my side. 

The test failing on Ubuntu HDRP is probably infrastructure related. Do your best to make it pass but I think it's an upgrade issue of HDRP that messes up with graphic code (Occlusion code for example). 

Check this test to add it to the ignore list if needed.
Tests.Runtime.CamerasBlendingTests.BlendingBetweenCameras

2022-06-06 13:41 UTC, merged