CMCL-1117: clipper namespace change to avoid conflicts
Unity-Technologies/com.unity.cinemachine pull request #522
Opened 2022-08-05 13:02 UTC by gaborkb

### Purpose of this PR
https://jira.unity3d.com/browse/CMCL-1117

- Replaced clipper library with release build built from the newest version (4.6).
- Changed Clipper's `ClipperLib` namespace to `Cinemachine.ClipperLib` to avoid namespace conflict with others who include clipper.
- dll is renamed

### Testing status

- [ ] Added an automated test
- [x] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk
Should check if performance degraded. Maybe new version of clipper is slower.

### Comments to reviewers

### Package version

2022-08-08 12:53 UTC, gaborkb commented on com.unity.cinemachine/Tests/Runtime/Cinemachine.Runtime.Tests.asmdef
> +        "cinemachine_clipper_library.dll"
Confiner2DUnitTests depend on clipper, and they failed after not including it in some editor versions.

2022-08-08 13:23 UTC, glabute approved these changes
How did you change the namespace from ClipperLib to Cinemachine.ClipperLib?  I only see a "using" difference

2022-08-08 14:21 UTC, glabute requested changes
Need to source-control the customization to clipper

2022-08-08 16:26 UTC, gaborkb commented
Yamato fails are due to splines package

2022-08-09 11:18 UTC, glabute approved these changes

2022-08-09 11:43 UTC, merged