allow equality of center point special case. Expose step size for fin…
Unity-Technologies/com.unity.cinemachine pull request #530
Opened 2022-08-10 05:30 UTC by gaborkb

…etuning

[Delete any line or section that does not apply]

### Purpose of this PR

[JIRA issue. Desc of feature/change. Links to screenshots, design docs, user docs, etc. Remember reviewers may be outside your team, and not know your feature/area that should be explained more.]

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automated test
- [ ] Passed all automated tests
- [ ] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

### Comments to reviewers

[Info per person for what to focus on, or historical info to understand who have previously reviewed and coverage. Help them get context.]

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

2022-08-10 12:46 UTC, glabute requested changes
Camera still moves (a little) in the sample scene, even at max quality.
I'm not convinced that this quality business is a good strategy for handling such edge cases.  0.000005f is an _insanely_ small step size.  Maybe we can have a discussion about how to solve this better.

2022-08-10 12:46 UTC, glabute commented on com.unity.cinemachine/Runtime/Core/ConfinerOven.cs
> +        const float k_MinStepSize = 0.005f, k_MaxStepSize = 0.000005f;
max is smaller than min?

2022-08-10 12:46 UTC, glabute commented on com.unity.cinemachine/Runtime/Core/ConfinerOven.cs
> +        float m_MinStepSize = k_MinStepSize;
should this be called m_StepSize or something like that?  It's a bit confusing between m_MinStepSize and k_MinStepSize.

2022-08-10 12:46 UTC, glabute commented on com.unity.cinemachine/Runtime/Behaviours/CinemachineConfiner2D.cs
> +                quality = (quality - k_QualityMin) / k_QualityMax; // normalize quality to [0-1]
Normalization is not guaranteed, because caller can pass anything for quality

2022-10-12 13:50 UTC, gaborkb commented
No longer relevant. See clipper2 in CM3

2022-10-12 13:50 UTC, closed without merging