CMCL-1059: Freelook and Collider don't work well together when transitioning between rigs
Unity-Technologies/com.unity.cinemachine pull request #532
Opened 2022-08-12 18:18 UTC by gaborkb

### Purpose of this PR
Parent issue: CMCL-1057 - has repro project.

The issue was that we were damping the displacement, but when colliding with a wall, this caused a strong overshot towards or away from the target.
I think, we should damp the delta between the previous camera position and the current instead.

This fix will need to be ported to 2.6, 2.9, 3.0.

TODO: have not tested with normal vcams!

### Testing status

- [ ] Added an automated test
- [x] Passed all automated tests
- [x] Manually tested with repro project and in freelook collider scene

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk
### Comments to reviewers
### Package version

2022-08-15 12:48 UTC, glabute requested changes
The reason that we damped the displacement and not the camera position is that it's important that the damping NOT apply to user-generated motion (e.g. user moves the mouse, result should not be damped).

2022-08-15 13:20 UTC, gaborkb commented
> The reason that we damped the displacement and not the camera position is that it's important that the damping NOT apply to user-generated motion (e.g. user moves the mouse, result should not be damped).

I think I came up with a solution over the weekend. I felt that this is not good solution in principle.

2022-08-15 13:39 UTC, glabute commented
I was thinking that a better solution might involve tracking the camera distance from target and making sure that it does not shrink when it should be growing or grow when it should be shrinking.

2022-08-16 15:21 UTC, closed without merging

2022-08-16 15:21 UTC, glabute commented
Replaced by https://github.com/Unity-Technologies/com.unity.cinemachine/pull/535