CMCL-1182: missing docs
Unity-Technologies/com.unity.cinemachine pull request #561
Opened 2022-09-09 17:58 UTC by gaborkb

### Purpose of this PR
Added docs based on this report: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/759bf7a1-6c2a-454c-a8a8-556226f16069%2Fpvp%2Fupm-ci~%2Fpvp/com.unity.cinemachine.json.

In some places, I changed the access modifier of the function/property that was missing docs. 

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [ ] Manually tested 

### Documentation status

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [x] Commented all public classes, properties, and methods
- [ ] Updated user documentation

2022-09-09 18:15 UTC, glabute requested changes

2022-09-09 18:15 UTC, glabute commented on com.unity.cinemachine/Editor/Utility/InspectorUtility.cs
> +        /// <returns>The nicified name</returns>
This entire class should internal

2022-09-09 18:15 UTC, glabute commented on com.unity.cinemachine/Runtime/Deprecated/CinemachinePathBase.cs
> +        void OnEnable() {} // to add enable toggle
Should be virtual protected, since this is a base class.

2022-09-09 19:48 UTC, glabute requested changes

2022-09-09 19:48 UTC, glabute commented on com.unity.cinemachine/Runtime/Deprecated/CinemachinePathBase.cs
> +        protected virtual void OnEnable() {} // to add enable toggle
doesn't this need XML doc now?

2022-09-10 00:33 UTC, gaborkb commented on com.unity.cinemachine/Runtime/Deprecated/CinemachinePathBase.cs
> +        protected virtual void OnEnable() {} // to add enable toggle
I don't think it needs it, but I added

2022-09-10 12:52 UTC, glabute approved these changes

2022-09-12 13:36 UTC, merged