CMCL-1195: Add HDRP tests for physical camera properties
Unity-Technologies/com.unity.cinemachine pull request #705
Opened 2022-12-09 16:05 UTC by gaborkb

### Purpose of this PR
[CMCL-1195](https://jira.unity3d.com/browse/CMCL-1195): Automated Test for camera physical properties on all supported versions of HDRP

- Added test that checks all physical properties and also if modifications are applied.
- Cleaned up HDRP specific asmdefs and test setup.
- Added RuntimeUtility test for our raycasts + minor cleanup in RuntimeUtility.

### Testing status

- [x] Added an automated test
- [x] Passed all automated tests
- [x] Manually tested 

### Documentation status
N/A

### Technical risk
### Comments to reviewers
### Package version

2022-12-21 14:43 UTC, glabute requested changes

2022-12-21 14:43 UTC, glabute commented on com.unity.cinemachine.hdrptests/Tests/Runtime/CheckPhysicalCameraProperties.cs
> +                Assert.That(m_Cam.sensorSize, Is.EqualTo(state.Lens.SensorSize));
Lots of repeated code in checking lens properties, susceptible to error.  Can checking lens properties be moved to a function?

2023-01-03 14:59 UTC, AntoineCharton approved these changes
Really nice idea!

2023-01-11 20:27 UTC, guillaumelevass approved these changes

2023-01-23 16:04 UTC, glabute approved these changes

2023-01-23 19:21 UTC, merged